name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Code Exists
        run: ls -la

      - name: Verify package.json
        run: cat package.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Set environment variables
        run: |
          echo "BOT_WAREHOUSE_TOKEN=${{ secrets.BOT_WAREHOUSE_TOKEN }}" >> $GITHUB_ENV
          echo "BOT_ORDERS_TOKEN=${{ secrets.BOT_ORDERS_TOKEN }}" >> $GITHUB_ENV
          echo "BOT_STATUS_TOKEN=${{ secrets.BOT_STATUS_TOKEN }}" >> $GITHUB_ENV
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Show installed packages
        run: npm list --depth=0

      - name: Start Application
        run: npm run start
